name: enhance
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - numpy
  - pandas
  - openai
  - pytorch
  - spacy
  - scikit-learn
  - tqdm
  - jupyter
  - ipykernel
  - transformers
  - pip:
    - git+https://github.com/openai/CLIP.git
    - git+https://github.com/huggingface/transformers
